// <auto-generated />
using System;
using ForumSchoolProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumSchoolProject.Migrations
{
    [DbContext(typeof(ProjektGContext))]
    partial class ProjektGContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForumSchoolProject.Models.Post", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pid"));

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PostDescription")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Uid")
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    b.HasKey("Pid");

                    b.HasIndex("Uid");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ForumSchoolProject.Models.User", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("int")
                        .HasColumnName("UserGroupID");

                    b.HasKey("Uid");

                    b.HasIndex("UserGroupId");

                    b.HasIndex(new[] { "Login" }, "UQ__Users__5E55825B8A13A7AB")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ForumSchoolProject.Models.UserGroup", b =>
                {
                    b.Property<int>("UserGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserGroupID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserGroupId"));

                    b.Property<string>("AddPosts")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("EditPost")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Gdescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GDescription");

                    b.HasKey("UserGroupId");

                    b.ToTable("UserGroup", (string)null);
                });

            modelBuilder.Entity("ForumSchoolProject.Models.Post", b =>
                {
                    b.HasOne("ForumSchoolProject.Models.User", "UidNavigation")
                        .WithMany("Posts")
                        .HasForeignKey("Uid")
                        .IsRequired()
                        .HasConstraintName("FK_Posts_Users");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("ForumSchoolProject.Models.User", b =>
                {
                    b.HasOne("ForumSchoolProject.Models.UserGroup", "UserGroup")
                        .WithMany("Users")
                        .HasForeignKey("UserGroupId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_UserGroup");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("ForumSchoolProject.Models.User", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("ForumSchoolProject.Models.UserGroup", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
